name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
#    #(optional) Run workflow when pushing on master/main
#   push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: R1 Brief Overview
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r1.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          base: header, introduction, activity, community, repositories
    
      - name: R2 Contributions
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r2.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
          plugin_followup: yes
          plugin_followup_sections: user
          config_order: notable, followup

      - name: R3 Interests
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r3.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 18587584
          plugin_topics: yes
          plugin_topics_mode: starred
          
      - name: R4 My Activity
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r4.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_repositories: yes
          plugin_repositories_featured: kaustav202
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          
          
      - name: R5 Community Activity on My Repo 
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r5.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_followup: yes
          plugin_people: yes
          plugin_people_types: followers, contributors, stargazers, watchers, sponsors
          plugin_people_identicons: yes
          plugin_people_size: 16
          plugin_traffic: yes
