name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: R1
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r1.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_charts: yes
          base: header, introduction, activity, community, repositories
    
      - name: R2
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r2.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_notable: yes
          config_order: notable, followup

      - name: R3
        uses: lowlighter/metrics@latest
        with:
          filename: git-metrics/r3.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 72179327
          plugin_topics: yes
          plugin_topics_mode: labels
          config_order: discussions, stackoverflow, topics
          
