name: Update README

on:
  schedule:
    - cron: "0 */18 * * *" # “At minute 0 past every 18th hour.”
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README with recent activity

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: Readme-Workflows/recent-activity@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "./.github/recent-activity.config.yml"
